### ISSUE TITLE
maybe simplify access to e, ctx, ctx.log

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/aws-util-firecloud#20]
rather than passing e.g. `ctx` around, just to able to call `ctx.log.error`, given the lambda's serial execution flow (one event at a time), maybe we could do

```js
import {e, ctx, log} from 'aws-util-firecloud/lib/lambda';

log.error(...)
```

wdyt @IanSavchenko ?

**Comment by IanSavchenko** [comment]
I would not do this, looks like not a good pattern to me. And it will make it harder to test.

**Comment by andreineculau** [comment]
decided IRL to only do it for `log`, and as a global var
