### ISSUE TITLE
feat: log if event loop is not empty when the lambda responds

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/aws-util-firecloud#25]
we had an instance where the lambda logged a response to AWS, but then it was waiting for the event loop to become empty, which never happened, thus the lambda timed out (and the initial response was ignored)

it would be good to at least log that "hey we are now replying to AWS. but this lambda is configured to wait until the event loop is empty, and there's smth on the event loop right now" - even better if we can report some useful info about what is actually on the event loop

currently there are only some undocumented nodejs APIs - `process._getActiveRequests()` and `process._getActiveHandles()` - and even those don't work as expected. I tried in a node REPL to run a simple async function that sleeps for 10 seconds then console.log-s smth and `process._getActiveRequests()` remained empty, while I was expecting it to report the async function somehow.

**Comment by andreineculau** [comment]
tried now also with a `setTimeout` - still empty array result from `process._getActiveRequests()`

**Comment by IanSavchenko** [comment]
This worked for me https://github.com/mafintosh/why-is-node-running

```js
let log = require('why-is-node-running');

setTimeout(function() {
  console.log('done!');
}, 2000);

log();
```

Outputs 
```
There are 1 handle(s) keeping the process running

# Timeout
/Users/isao/code/github/TobiiPro/atex-platform/test.js:3 - setTimeout(function() {
```

**Comment by andreineculau** [comment]
👏 I thought async_hooks came in nodejs 10, but i see now it's also in nodejs 8

don't know if it's in the version that aws delivers, but it's worth a try

**Comment by andreineculau** [comment]
closing without new functionality in aws-util-firecloud. *when* a lambda times out and needs investigation, one can wrap the lambda and diagnose with the help of `_.getV8OpenHandles()`
