### ISSUE TITLE
remove cors() from lambda express, maybe reexport cors module

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/aws-util-firecloud#27]
We discussed that it should be up to the API lambda itself to setup CORS, so need to remove it here, mark the change as breaking and update lambdas.

Regarding reexporting CORS: I wouldn't do it, because clients get to decide which version to use and type-inference will probably work better (if we decide to use TS in lambda at some point).

**Comment by andreineculau** [comment]
closing. the expressApp (that is accessible in a express-bootstrapped lambda handler) now surfaces a property defaultMiddlewares. those middlewares can now be manipulated

```js
import cors from 'cors';

import {
  bootstrap
} from 'aws-util-firecloud/lib/express';

export let handle = bootstrap(async function(app, _e, _ctx) {
  app.defaultMiddlewares.cors.disable();
  app.use(cors(...));
});
```
